easy_admin:
    design:
      menu:
        - { label: 'Homepage', route: home, rel: 'index' }
        - Photo
    entities:
      Photo:
        class: App\Entity\Photo
        list:
           fields:
             - { label: 'image', property: 'filename', type: 'image', base_path: '/images/' }
             - title
             - description
             - mural
